const modules={
estudiantes:{n:'Estudiantes',i:'🎓',d:'Registra y consulta los estudiantes.',e:'/estudiantes/',f:[['nombre','Nombre','text'],['apellido','Apellido','text'],['documento','Documento','text'],['grado','Grado','text'],['direccion','Dirección','textarea'],['acudiente_id','Acudiente','select','acudientes']]},
conductores:{n:'Conductores',i:'🧑‍✈️',d:'Administra los conductores disponibles.',e:'/conductores/',f:[['nombre','Nombre','text'],['apellido','Apellido','text'],['documento','Documento','text'],['licencia','Licencia','text'],['telefono','Teléfono','tel'],['activo','Estado','boolean']]},
vehiculos:{n:'Vehículos',i:'🚌',d:'Controla la flota de transporte.',e:'/vehiculos/',f:[['placa','Placa','text'],['marca','Marca','text'],['modelo','Modelo','text'],['capacidad','Capacidad','number'],['estado','Estado','static',['Disponible','En mantenimiento','No disponible']]]},
rutas:{n:'Rutas',i:'🛣️',d:'Configura las rutas escolares.',e:'/rutas/',f:[['nombre','Nombre de la ruta','text'],['descripcion','Descripción','textarea'],['hora_salida','Hora de salida','time'],['hora_llegada','Hora de llegada','time'],['conductor_id','Conductor','select','conductores'],['vehiculo_id','Vehículo','select','vehiculos'],['estado','Estado','static',['Activa','Inactiva']]]},
paraderos:{n:'Paraderos',i:'📍',d:'Administra los puntos de recogida.',e:'/paraderos/',f:[['nombre','Nombre','text'],['direccion','Dirección','text'],['referencia','Referencia','textarea'],['latitud','Latitud','number'],['longitud','Longitud','number']]},
acudientes:{n:'Acudientes',i:'👪',d:'Gestiona los responsables de estudiantes.',e:'/acudientes/',f:[['nombre','Nombre','text'],['apellido','Apellido','text'],['documento','Documento','text'],['telefono','Teléfono','tel'],['correo','Correo','email'],['usuario_id','Usuario','select','usuarios']]},
usuarios:{n:'Usuarios',i:'👤',d:'Administra los usuarios del sistema.',e:'/usuarios/',f:[['nombre','Nombre','text'],['apellido','Apellido','text'],['correo','Correo','email'],['telefono','Teléfono','tel'],['rol_id','Rol','select','roles']]},
roles:{n:'Roles',i:'🔐',d:'Define los roles de acceso.',e:'/roles/',f:[['nombre','Nombre','text'],['descripcion','Descripción','textarea']]},
asignaciones:{n:'Asignaciones',i:'🔗',d:'Asigna estudiantes a las rutas y paraderos.',e:'/estudiante-ruta/',f:[['estudiante_id','Estudiante','select','estudiantes'],['ruta_id','Ruta','select','rutas'],['paradero_id','Paradero','select','paraderos']]},
abordajes:{n:'Registros de abordaje',i:'✓',d:'Registra entradas y salidas de estudiantes.',e:'/registros-abordaje/',f:[['estudiante_id','Estudiante','select','estudiantes'],['ruta_id','Ruta','select','rutas'],['tipo','Tipo','static',['Entrada','Salida']]]}
};
let key=null,rows=[],editId=null,timer;const $=x=>document.getElementById(x);
// Si FastAPI entrega la página usa el mismo origen; desde Live Server usa la API local.
const API_BASE=window.API_BASE_URL??(location.protocol==='file:'||location.port==='5500'||location.port==='8443'?'http://127.0.0.1:8000':'');
async function api(url,opt={}){const r=await fetch(`${API_BASE}${url}`,opt);if(!r.ok){let m='No fue posible completar la operación.';try{m=(await r.json()).detail||m}catch{}throw Error(m)}return r.status===204?null:r.json()}
function navigation(){$('navigation').innerHTML=`<button class="nav-button active" data-k="home">⌂ &nbsp; Panel principal</button>${Object.entries(modules).map(([k,m])=>`<button class="nav-button" data-k="${k}">${m.i} &nbsp; ${m.n}</button>`).join('')}`;$('navigation').onclick=e=>{const b=e.target.closest('[data-k]');if(b)openModule(b.dataset.k)}}
async function openModule(k){document.querySelectorAll('.nav-button').forEach(x=>x.classList.toggle('active',x.dataset.k===k));document.querySelector('.sidebar').classList.remove('open');if(k==='home'){key=null;$('dashboard').classList.remove('hidden');$('module').classList.add('hidden');$('pageTitle').textContent='Panel principal';return dashboard()}key=k;const m=modules[k];$('dashboard').classList.add('hidden');$('module').classList.remove('hidden');$('pageTitle').textContent=m.n;$('moduleLabel').textContent=m.n.toUpperCase();$('moduleTitle').textContent=m.n;$('moduleDescription').textContent=m.d;load()}
async function dashboard(){const list=Object.entries(modules).slice(0,4);$('summaryCards').innerHTML=list.map(([,m])=>`<article class="summary-card"><p>${m.i} ${m.n}</p><strong>—</strong></article>`).join('');await Promise.all(list.map(async([,m],i)=>{try{$('summaryCards').children[i].querySelector('strong').textContent=(await api(m.e)).length}catch{}}))}
async function load(){$('tableBody').innerHTML='<tr><td class="empty">Cargando datos...</td></tr>';try{rows=await api(modules[key].e);render()}catch(e){$('tableBody').innerHTML=`<tr><td class="empty">${e.message}</td></tr>`;$('recordCount').textContent='Error al cargar'}}
function value(v){return v===null||v===undefined||v===''?'—':typeof v==='boolean'?(v?'Activo':'Inactivo'):String(v)}
function render(){const m=modules[key],cols=[['id','ID'],...m.f.map(x=>[x[0],x[1]])];$('tableHead').innerHTML=`<tr>${cols.map(x=>`<th>${x[1]}</th>`).join('')}<th>Acciones</th></tr>`;$('recordCount').textContent=`${rows.length} registro${rows.length===1?'':'s'}`;const actions=r=>key==='roles'?'—':`<button class="action-button" data-edit="${r.id}">Editar</button><button class="action-button delete-button" data-del="${r.id}">Eliminar</button>`;$('tableBody').innerHTML=rows.length?rows.map(r=>`<tr>${cols.map(x=>`<td>${value(r[x[0]])}</td>`).join('')}<td>${actions(r)}</td></tr>`).join(''):`<tr><td class="empty" colspan="${cols.length+1}">Aún no hay registros. Crea el primero.</td></tr>`}
async function select(field,val){const el=document.querySelector(`[name="${field[0]}"]`);let options=[];if(field[2]==='static')options=field[3].map(x=>[x,x]);else{try{options=(await api(modules[field[3]].e)).map(x=>[x.id,x.nombre?`${x.nombre}${x.apellido?' '+x.apellido:''}`:x.placa||`#${x.id}`])}catch{}}el.innerHTML=`<option value="">Selecciona una opción</option>${options.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}`;if(val!=null)el.value=val}
async function form(id){const m=modules[key],data=id?rows.find(x=>x.id===id):{};editId=id;$('dialogLabel').textContent=id?'EDITAR REGISTRO':'NUEVO REGISTRO';$('dialogTitle').textContent=`${id?'Editar':'Crear'} registro`;$('saveButton').textContent=id?'Guardar cambios':'Crear registro';$('formFields').innerHTML=m.f.map(([n,l,t])=>{if(t==='textarea')return `<div class="field full"><label>${l}</label><textarea name="${n}">${data[n]??''}</textarea></div>`;if(t==='boolean')return `<div class="field"><label>${l}</label><select name="${n}"><option value="true">Activo</option><option value="false">Inactivo</option></select></div>`;if(t==='select'||t==='static')return `<div class="field"><label>${l}</label><select name="${n}"></select></div>`;return `<div class="field"><label>${l}</label><input name="${n}" type="${t}" value="${data[n]??''}"></div>`}).join('');$('recordDialog').showModal();for(const f of m.f.filter(x=>x[2]==='select'||x[2]==='static'))await select(f,data[f[0]]);if(data.activo!==undefined)document.querySelector('[name=activo]').value=String(data.activo)}
function toast(m,b=false){const t=$('toast');t.textContent=m;t.className=`toast visible${b?' error':''}`;clearTimeout(timer);timer=setTimeout(()=>t.className='toast',3500)}
async function save(e){e.preventDefault();const payload={};for(const [n,,t] of modules[key].f){let v=new FormData(e.target).get(n);if(v===''&&!['text','textarea'].includes(t))v=null;if(t==='number'&&v!==null)v=Number(v);if(t==='select'&&v!==null)v=Number(v);if(t==='boolean')v=v==='true';payload[n]=v}try{await api(editId?`${modules[key].e}${editId}`:modules[key].e,{method:editId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('recordDialog').close();toast(editId?'Registro actualizado correctamente.':'Registro creado correctamente.');load()}catch(e){toast(e.message,true)}}
async function remove(id){try{await api(`${modules[key].e}${id}`,{method:'DELETE'});toast('Registro eliminado correctamente.');load()}catch(e){toast(e.message,true)}}
document.addEventListener('DOMContentLoaded',()=>{navigation();$('newButton').onclick=()=>form();$('refreshButton').onclick=load;$('closeDialog').onclick=()=>$('recordDialog').close();$('cancelButton').onclick=()=>$('recordDialog').close();$('recordForm').onsubmit=save;$('tableBody').onclick=e=>{if(e.target.dataset.edit)form(Number(e.target.dataset.edit));if(e.target.dataset.del&&confirm('¿Seguro que deseas eliminar este registro?'))remove(Number(e.target.dataset.del))};$('menuButton').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');openModule('home')});
